Add resources configuration for wait-for-migration initcontainer, migration job
openfga/helm-charts pull request #73
Opened 2023-10-25 08:14 UTC by marlenekoh

Allow resources limits and requests to be configured for the migration job.

## Description

Added the following to values.yaml
```diff
datastore:
   engine: memory
   uri:
   uriSecret:
   maxCacheSize:
   maxOpenConns:
   maxIdleConns:
   connMaxIdleTime:
   connMaxLifetime:
   applyMigrations: true
+  migrations:
+    resources: {}
```

## References

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2023-11-02 20:10 UTC, jpadilla requested changes

2023-11-02 20:10 UTC, jpadilla commented on charts/openfga/templates/deployment.yaml
> +            {{- toYaml .Values.resources | nindent 12 }}
Is this supposed to be `.Values.datastore.migrations.resources` instead?

2023-11-03 05:51 UTC, rhamzeh approved these changes

2023-11-04 18:31 UTC, jpadilla approved these changes

2023-11-04 18:31 UTC, merged